### PR TITLE
Rename scalar to konst

### PR DESCRIPTION
**Pull request by tomjaguarpaw**
Closes https://github.com/Mikolaj/horde-ad/issues/29#issuecomment-1112388139

If merging, please delete the source branch.

### CODE REVIEW

**Comment by Mikolaj** [comment]
Oh dear, I probably totally miscommunicated? I meant "constant" does not lead to confusion, because instead of "constant" we use "konst*" everywhere. So, I thought your proposal to use "constant" was spot on. :)

**Comment by tomjaguarpaw** [comment]
OK, no problem. How about this?

**Review by Mikolaj — APPROVED** [review]
Perfect (if CI agrees).

**Comment by Mikolaj** [comment]
Merging. Thank you!

**Pull request merged**
